language: ruby
cache: bundler
rvm:
  - "2.2"
  - "ruby-head"

matrix:
  allow_failures:
    - rvm:
      - "ruby-head"
  fast_finish: true
notifications:
  email:
    - travis-ci@sorah.jp
script: bundle exec rspec -fd ./spec
sudo: false
